context:
  version: "0.17.29"

package:
  name: svelte-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/svelte-language-server/-/svelte-language-server-${{ version }}.tgz
  sha256: eeb083b9467dbe46a298001c3f3be0f65a116577e1b3890fdc4dd7edef0c290a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - svelteserver --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Svelte Language Server
  homepage: https://github.com/sveltejs/language-tools
  repository: https://github.com/sveltejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
